"""update occurrence to includes severity and image columns

Revision ID: a15d18326b75
Revises: 73612824be72
Create Date: 2025-11-28 01:01:37.347979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a15d18326b75'
down_revision: Union[str, Sequence[str], None] = '73612824be72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('severities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.add_column('occurrences', sa.Column('image_path', sa.String(length=255), nullable=True))
    op.add_column('occurrences', sa.Column('severity_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'occurrences', 'severities', ['severity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'occurrences', type_='foreignkey')
    op.drop_column('occurrences', 'severity_id')
    op.drop_column('occurrences', 'image_path')
    op.drop_table('severities')
    # ### end Alembic commands ###
